# This workflow checks the links in plaintext and HTML files
name: Check links

on:
  # Uncomment the 'pull_request' line below to trigger the workflow in PR
  pull_request:
  # Schedule runs on 12 noon every Sunday
  schedule:
    - cron: '0 12 * * 0'

jobs:
  check_links:
    name: Check links
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2.3.4
      with:
        ref: master
        path: repository

    - name: Checkout the documentation
      uses: actions/checkout@v2.3.4
      with:
        ref: gh-pages
        path: documentation

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1.0.3
      with:
        args: --accept 429 --exclude "^https://zenodo.org/badge/DOI/$" --exclude "https://www.generic-mapping-tools.org/_static/gmt-logo.png/*" --exclude "``@ridge.txt" --verbose "repository/**/*.rst" "repository/**/*.md" "documentation/dev/**/*.html"
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Show output
      run: cat /tmp/lychee/out.md
